import os
import time
import uuid
import json

from flask import Flask, request, jsonify
from flask_cors import CORS

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None  # Will fail at runtime if not installed


app = Flask(__name__)

FRONTEND_URL = os.getenv("FRONTEND_URL")
if FRONTEND_URL:
    CORS(app, origins=[FRONTEND_URL])
else:
    CORS(app)


SESSIONS = {}
SESSION_TTL_SECONDS = 60 * 60  # 1 hour


def cleanup_sessions():
    now = time.time()
    to_delete = []
    for token, data in SESSIONS.items():
        if now - data.get("created_at", now) > SESSION_TTL_SECONDS:
            to_delete.append(token)
    for token in to_delete:
        SESSIONS.pop(token, None)


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


@app.route("/start-session", methods=["POST"])
def start_session():
    """Creates a single-use session token (one GENERATE attempt)."""
    cleanup_sessions()
    token = str(uuid.uuid4())
    SESSIONS[token] = {
        "used": False,
        "created_at": time.time(),
    }
    return jsonify({"session_token": token})


@app.route("/generate", methods=["POST"])
def generate():
    cleanup_sessions()

    data = request.get_json(silent=True) or {}

    product = (data.get("product") or "").strip()
    description = (data.get("description") or "").strip()
    size = (data.get("size") or "").strip()
    session_token = (data.get("session_token") or "").strip()
    dev_mode = bool(data.get("dev_mode"))

    ui_sizes = {"1024x1024", "1024x1792", "1792x1024"}

    if not product:
        return jsonify(
            {
                "ok": False,
                "error": "missing_product",
                "message": "Missing product name.",
                "button_enabled": not dev_mode,
            }
        ), 400

    if product == "4242":
        dev_mode = True

    if size not in ui_sizes:
        return jsonify(
            {
                "ok": False,
                "error": "invalid_size",
                "message": "Size must be 1024x1024, 1024x1792, or 1792x1024.",
                "button_enabled": not dev_mode,
            }
        ), 400

    if not dev_mode:
        if not session_token or session_token not in SESSIONS:
            return jsonify(
                {
                    "ok": False,
                    "error": "invalid_token",
                    "message": "No valid attempt is available for this session.",
                    "button_enabled": False,
                }
            ), 403

        session_data = SESSIONS[session_token]
        if session_data.get("used"):
            return jsonify(
                {
                    "ok": False,
                    "error": "no_attempt_left",
                    "message": "This session has already used its single attempt.",
                    "button_enabled": False,
                }
            ), 403

        session_data["used"] = True

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key or OpenAI is None:
        return jsonify(
            {
                "ok": False,
                "error": "missing_api_key",
                "message": "Server is not configured with OPENAI_API_KEY.",
                "button_enabled": dev_mode,
            }
        ), 500

    text_model = os.getenv("OPENAI_TEXT_MODEL", "gpt-4.1-mini")
    image_model = os.getenv("OPENAI_IMAGE_MODEL") or "gpt-image-1"
    image_model_lower = image_model.lower()

    # Increase HTTP timeout so Render + OpenAI have time to answer
    client = OpenAI(api_key=api_key, timeout=120.0)

    # ---------- TEXT (CHAT COMPLETIONS JSON MODE) ----------
    system_msg = (
        "You are an ad-creative system for the ACE advertising platform. "
        "You must respond ONLY with valid JSON matching the requested schema."
    )

    user_msg = (
        "Product: " + product + "\n"
        "Description: " + (description or "N/A") + "\n\n"
        "Create 3 different short English ad headlines and 3 English marketing texts.\n"
        "Rules:\n"
        "- Headlines: 3–7 words, punchy, related to the product and to a clear, simple visual metaphor.\n"
        "- Each marketing text must be a single paragraph of about 50 words (40–60 words range).\n"
        "- Do NOT mention AI, ACE, or any engine.\n"
        "- Do NOT talk about being generated by a system or model.\n\n"
        "Return the result as STRICT JSON with this schema (and nothing else):\n"
        "{\n"
        "  \"variants\": [\n"
        "    {\"headline\": \"...\", \"body\": \"...\"},\n"
        "    {\"headline\": \"...\", \"body\": \"...\"},\n"
        "    {\"headline\": \"...\", \"body\": \"...\"}\n"
        "  ]\n"
        "}\n"
    )

    try:
        completion = client.chat.completions.create(
            model=text_model,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system_msg},
                {"role": "user", "content": user_msg},
            ],
        )

        content = completion.choices[0].message.content
        text_json = json.loads(content)
        variants = text_json.get("variants", [])
        if len(variants) != 3:
            raise ValueError("Unexpected JSON from text model (need exactly 3 variants).")

    except Exception as e:
        return jsonify(
            {
                "ok": False,
                "error": "text_generation_error",
                "message": "Failed to create headlines and copy.",
                "details": str(e),
                "button_enabled": dev_mode,
            }
        ), 500

    # ---------- IMAGE GENERATION ----------

    def map_size_for_model(ui_size: str) -> str:
        if "gpt-image-1" in image_model_lower:
            if ui_size == "1024x1024":
                return "1024x1024"
            if ui_size == "1024x1792":
                return "1024x1536"
            if ui_size == "1792x1024":
                return "1536x1024"
            return "1024x1024"
        if "dall-e-3" in image_model_lower:
            if ui_size in {"1024x1024", "1024x1792", "1792x1024"}:
                return ui_size
            return "1024x1024"
        return "1024x1024"

    openai_size = map_size_for_model(size)

    # Build one combined prompt for 3 variations to reduce latency
    headlines_list = [ (v.get("headline") or "").strip() for v in variants ]
    headlines_text = "; ".join(h for h in headlines_list if h)

    base_prompt = (
        "Ultra realistic advertising photos for the product '" + product + "'.\n"
        "Create 3 different ad variations. In each image, use exactly two physical objects only.\n"
        "Show them either merged as one clear, dominant form or tightly side by side "
        "to emphasize a strong similarity in shape.\n"
        "The background in every image must be the classic, natural environment of one of the objects.\n"
        "Avoid extra decorative items. Only those two objects are visible.\n"
        "If any text appears in an image, it must be at most one short English headline, "
        "and no other words or slogans.\n"
        "Leave comfortable empty space around the main objects so a headline could exist "
        "without touching the frame edges.\n"
    )

    if headlines_text:
        base_prompt += (
            "Take creative inspiration from these headlines: " + headlines_text + ". "
            "Each of the 3 generated images should feel like a different interpretation of these ideas.\n"
        )

    image_urls = []
    try:
        kwargs = {
            "model": image_model,
            "prompt": base_prompt,
            "n": 3,
            "size": openai_size,
        }
        if "dall-e-3" in image_model_lower:
            kwargs["response_format"] = "url"

        img_response = client.images.generate(**kwargs)

        for img_obj in img_response.data:
            url = getattr(img_obj, "url", None)
            if not url:
                b64 = getattr(img_obj, "b64_json", None)
                if b64:
                    url = "data:image/png;base64," + b64
                else:
                    raise ValueError("Image response missing both url and b64_json.")
            image_urls.append(url)

        if len(image_urls) != 3:
            raise ValueError("Expected exactly 3 images from the image model.")

    except Exception as e:
        return jsonify(
            {
                "ok": False,
                "error": "image_generation_error",
                "message": "Failed to create images.",
                "details": str(e),
                "button_enabled": dev_mode,
            }
        ), 500

    packaged_variants = []
    for idx, variant in enumerate(variants):
        packaged_variants.append(
            {
                "headline": (variant.get("headline") or "").strip(),
                "body": (variant.get("body") or "").strip(),
                "image_url": image_urls[idx] if idx < len(image_urls) else None,
            }
        )

    return jsonify(
        {
            "ok": True,
            "dev_mode": dev_mode,
            "variants": packaged_variants,
            "button_enabled": dev_mode,
        }
    )


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", "5000")))
